(() => {
  const FEATURES=['meanDwellTime','meanFlightTime','mouseCurvature','mouseMaxVelocity','focusBlurDelay','clickHoldDuration'];
  const finite=n=>Number.isFinite(n)?n:0;
  const REL_FLOOR_PCT=0.18;
  const ABS_FLOOR_STD={meanDwellTime:20,meanFlightTime:25,mouseCurvature:2.5,mouseMaxVelocity:2.5,focusBlurDelay:35,clickHoldDuration:20};
  const REL_FLOOR_OVERRIDE={mouseCurvature:0.5,mouseMaxVelocity:0.6};
  const mean=a=>a.length?a.reduce((s,x)=>s+x,0)/a.length:0;
  const std=a=>a.length<2?0:Math.sqrt(mean(a.map(x=>(x-mean(a))**2)));
  const regularize=(cov,mu)=>cov.map((r,i)=>r.map((v,j)=>{if(i!==j)return v;const key=FEATURES[i];const pct=REL_FLOOR_OVERRIDE[key]??REL_FLOOR_PCT;const relStd=pct*Math.abs(mu[key]);const floor=Math.max(ABS_FLOOR_STD[key]??1,relStd)**2;const scale=Math.max(Math.abs(v),1,(Math.abs(mu[key])*0.05)**2);return Math.max(finite(v)+0.05*scale,floor)+1e-6}));
  function invert(m){const n=m.length,a=m.map((r,i)=>[...r,...Array.from({length:n},(_,j)=>i===j?1:0)]);for(let c=0;c<n;c++){let p=c;for(let r=c+1;r<n;r++)if(Math.abs(a[r][c])>Math.abs(a[p][c]))p=r;if(Math.abs(a[p][c])<1e-6)return null;[a[c],a[p]]=[a[p],a[c]];const d=a[c][c];for(let j=0;j<2*n;j++)a[c][j]/=d;for(let r=0;r<n;r++){if(r===c)continue;const f=a[r][c];for(let j=0;j<2*n;j++)a[r][j]-=f*a[c][j]}}return a.map(r=>r.slice(n))}
  function quad(v,m){return v.reduce((s,x,i)=>s+x*m[i].reduce((q,z,j)=>q+z*v[j],0),0)}
  function bot(f){const r=[];if(!f.trusted)r.push('untrusted event');if(f.flights>=4&&f.flightStdDev<Math.max(8,f.meanFlightTime*0.08))r.push('near-constant key timing');if(f.flights>=8&&f.entropy<0.3)r.push('low timing entropy');if(f.points>=8&&f.mouseCurvature>0&&f.mouseCurvature<1.0006)r.push('linear pointer path');return r.length?{bot:true,reason:r.join(', ')}:{bot:false,reason:''}}
  class Tracker{constructor(form){this.form=form;this.ins=[...form.querySelectorAll('input')];this.reset()}reset(){this.down=new Map();this.lastUp=null;this.dw=[];this.fl=[];this.pts=[];this.vel=[];this.focus=[];this.lastFocus=null;this.holds=[];this.pd=null;this.trusted=true}start(){this.reset();this.kd=e=>{this.trusted&&=e.isTrusted;const t=performance.now();this.down.set(e.code,t);if(this.lastUp!==null)this.fl.push(t-this.lastUp)};this.ku=e=>{this.trusted&&=e.isTrusted;const t=performance.now(),d=this.down.get(e.code);if(d!==undefined)this.dw.push(t-d);this.lastUp=t};this.mv=e=>{this.trusted&&=e.isTrusted;const t=performance.now(),p={x:e.clientX,y:e.clientY,t},q=this.pts.at(-1);if(q){const d=Math.hypot(p.x-q.x,p.y-q.y),dt=t-q.t;if(dt>0&&d>0)this.vel.push(d/dt)}this.pts.push(p)};this.fc=e=>{this.trusted&&=e.isTrusted;const t=performance.now();if(this.lastFocus!==null)this.focus.push(t-this.lastFocus);this.lastFocus=t;this.lastUp=null};this.pd=e=>{this.trusted&&=e.isTrusted;this.pdT=performance.now()};this.pu=e=>{this.trusted&&=e.isTrusted;if(this.pdT!==undefined)this.holds.push(performance.now()-this.pdT);this.pdT=undefined};this.ins.forEach(i=>{i.addEventListener('keydown',this.kd);i.addEventListener('keyup',this.ku);i.addEventListener('focus',this.fc)});document.addEventListener('pointermove',this.mv,{passive:true});this.form.addEventListener('pointerdown',this.pd);this.form.addEventListener('pointerup',this.pu);return this}stop(){this.ins.forEach(i=>{i.removeEventListener('keydown',this.kd);i.removeEventListener('keyup',this.ku);i.removeEventListener('focus',this.fc)});document.removeEventListener('pointermove',this.mv);this.form.removeEventListener('pointerdown',this.pd);this.form.removeEventListener('pointerup',this.pu)}features(){const a=this.fl,avg=mean,entropy=()=>{if(a.length<4)return 1;const bins=Array(8).fill(0),m=Math.max(avg(a),1);a.forEach(v=>bins[Math.min(7,Math.floor(v/m*4))]++);return -bins.reduce((s,n)=>{if(!n)return s;const p=n/a.length;return s+p*Math.log2(p)},0)/3};let arc=0;for(let i=1;i<this.pts.length;i++)arc+=Math.hypot(this.pts[i].x-this.pts[i-1].x,this.pts[i].y-this.pts[i-1].y);const x=this.pts[0],y=this.pts.at(-1),direct=x&&y?Math.hypot(y.x-x.x,y.y-x.y):0;return{meanDwellTime:avg(this.dw),meanFlightTime:avg(a),flightStdDev:std(a),mouseCurvature:direct>2?arc/direct:0,mouseMaxVelocity:Math.max(0,...this.vel),focusBlurDelay:avg(this.focus),clickHoldDuration:avg(this.holds),trusted:this.trusted,flights:a.length,points:this.pts.length,entropy:entropy()}}}
  async function getProfile(){return new Promise(r=>chrome.storage.local.get('bioprint_profile',x=>r(x.bioprint_profile||null)))}
  function evaluate(live,p){const b=bot(live);if(b.bot)return{ok:false,bot:true,reason:b.reason,score:0};const mu=FEATURES.map(k=>finite(p.mean[k]));const v=FEATURES.map((k,i)=>finite(live[k])-mu[i]);const inv=p.inverseCovariance||invert(regularize(p.covariance, p.mean));const d=Math.sqrt(Math.max(0,quad(v,inv)));const score=Math.round(100*Math.exp(-0.5*(Math.min(d,20)/3)**2));return{ok:score>=42,bot:false,score,reason:score>=42?'Behavioral fingerprint matched.':'Behavioral mismatch detected.',distance:d}}
  function banner(text,ok){let b=document.getElementById('bioprint-extension-banner');if(!b){b=document.createElement('div');b.id='bioprint-extension-banner';Object.assign(b.style,{position:'fixed',top:'18px',right:'18px',zIndex:2147483647,padding:'12px 16px',borderRadius:'12px',font:'600 14px system-ui',boxShadow:'0 8px 30px rgba(0,0,0,.25)',color:'#fff'});document.documentElement.appendChild(b)}b.style.background=ok?'#0f766e':'#b91c1c';b.textContent=`BioPrint · ${text}`;clearTimeout(b._t);b._t=setTimeout(()=>b.remove(),3500)}
  async function attach(form){if(form.dataset.bioprintAttached)return;form.dataset.bioprintAttached='1';const tracker=new Tracker(form).start();form.addEventListener('submit',async e=>{if(form.dataset.bioprintPassed==='1'){delete form.dataset.bioprintPassed;return}e.preventDefault();e.stopImmediatePropagation();const p=await getProfile();if(!p){banner('No enrolled profile — enroll in the extension popup',false);return}const r=evaluate(tracker.features(),p);if(r.ok){banner(`ACCESS GRANTED · ${r.score}%`,true);form.dataset.bioprintPassed='1';tracker.stop();form.requestSubmit()}else banner(r.bot?'BOT BLOCKED':`ACCESS DENIED · ${r.score}%`,false)},true)}
  function scan(){document.querySelectorAll('form[data-bioprint-login]').forEach(attach)}
  scan();new MutationObserver(scan).observe(document.documentElement,{subtree:true,childList:true});
})();
